# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-1e2a1357-0907-48b4-b31c-2c80c8c079de";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-1e2a1357-0907-48b4-b31c-2c80c8c079de".device =
    "/dev/disk/by-uuid/1e2a1357-0907-48b4-b31c-2c80c8c079de";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/29DA-0D38";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-5b0f2317-9fd0-4ab0-8b27-3eb3d8a3161c"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
